# .github/workflows/ci.yml (BỔ SUNG)

name: CI/CD Spring Boot Build & Deploy

on:
  push:
    branches:
      - main

env:
  # Tên Image trên GHCR
  IMAGE_NAME: baitapspringbootmvc
  REGISTRY: ghcr.io
  # Cần THAY THẾ bằng thông tin GitOps Repo của bạn
  GITOPS_REPO: your-username/BaiTapSpringBootMVC-k8s
  GITOPS_PATH: k8s-manifests

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Cần quyền này để checkout và commit vào GitOps repo
      packages: write
    
    steps:
      # Bước 1-6 (Giữ nguyên như hướng dẫn trước) - Checkout, Setup Java, Build JAR, Setup Docker, Login GHCR, Build & Push Image
      # ... (Các bước 1 đến 6 ở hướng dẫn trước) ...

      # *** BƯỚC MỚI: CẬP NHẬT GITOPS REPO ***
      - name: 7. Cập nhật image tag trong GitOps Repository
        uses: karulis/image-tag-updater@v1.1.0 # Sử dụng một Action chuyên dụng
        with:
          # Token có quyền ghi vào GitOps Repo (đã tạo ở B2)
          GITHUB_TOKEN: ${{ secrets.GIT_OPS_TOKEN }}
          # Đường dẫn của GitOps Repo
          REPOSITORY_NAME: ${{ env.GITOPS_REPO }}
          # Đường dẫn đến file kustomization.yaml
          FILE_PATH: ${{ env.GITOPS_PATH }}/kustomization.yaml
          # Tên image trong kustomization.yaml (phải khớp)
          IMAGE_NAME: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          # Tag mới (sử dụng SHA của commit hiện tại)
          NEW_TAG: ${{ github.sha }}
          # Commit message
          COMMIT_MESSAGE: 'CI: Update ${{ env.IMAGE_NAME }} image to ${{ github.sha }}'

      # Thêm bước để push tag 'latest'
      - name: 8. Cập nhật tag 'latest' trong GitOps Repo (Tùy chọn)
        uses: karulis/image-tag-updater@v1.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GIT_OPS_TOKEN }}
          REPOSITORY_NAME: ${{ env.GITOPS_REPO }}
          FILE_PATH: ${{ env.GITOPS_PATH }}/kustomization.yaml
          IMAGE_NAME: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          NEW_TAG: latest # Luôn giữ tag 'latest' trỏ đến SHA mới nhất
          COMMIT_MESSAGE: 'CI: Update latest tag for ${{ env.IMAGE_NAME }}'